[build]
  base = "FrontendMentor/qr-code-component-main/my-react-app"
  publish = "FrontendMentor/qr-code-component-main/my-react-app/dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
